module.exports = `
<h1>Learn to fly with online drone classes</h1>
<p>Whether your goal is to take some epic pictures on the weekend or to engineer the next generation of unmanned aerial technology, there are online programs that can help. Of course, when it comes to physical flying skills, there’s no substitute for practice, but if you’re looking to take your UAV hobby to the next level, this is an option worth considering. </p>
<h2>Are online UAV programs high quality?</h2>
<p><img class="left" alt="online drone pilot training" src="/images/online-school.jpg"/>It’s normal to question whether an online program will provide the same quality of education as a more traditional in-person program. The truth is, quality varies no matter what type of training you choose. Your experience will depend on your goals, your learning style, and your ability to engage with the material. Rest assured, though, that there are graduates of online UAV programs out there earning six figure incomes (<a href="http://nypost.com/2014/11/25/get-a-degree-in-drones-and-earn-100000-a-year/">NYPost</a>). In fact, Unmanned Vehicle University, which incorporates online learning into most of its programs, reports an average salary of $104,000 for its graduates (<a href="http://www.uxvuniversity.com/faq/">UXUniversity.com</a>).</p>
<p>To make sure you get the best bang for your buck, verify that your instructor has years of experience as a certified pilot, and that he or she will be available for one-on-one consultation. The same goes for <a href="/drone-license-classes">in-person training programs</a>. It also never hurts to read reviews from graduates before you sign up.</p>
<h2>How do online and in-person training programs differ?</h2>
<p>Today, most schools offer online courses (<a href="http://www.babson.edu/academics/faculty/provost/pages/babson-survey-research-group.aspx">Babson Research Group</a>) and almost a third of students enrolled in higher education programs report that they are taking at least one class online. Even in-person courses generally include online components, so in reality the distinction between online and in-person learning isn’t black and white. </p>
<p>For UAV programs specifically, the biggest difference is that you won’t get hands-on or simulated flight experience in an online program. Instead, coursework will focus on academics. The upside of this arrangement is that schools don’t need to provide physical facilities, so online courses can be offered at a significant cost savings - plus you can work at your own pace.</p>
`;
