module.exports = `<h1>FAA Part 107 Remote Pilot Test</h1>
<p>If you’re researching how to become a certified drone pilot, you’ve probably heard about the Part 107 Remote Pilot Knowledge Test. What is it, what does it cover, how hard is it, and how can you prepare? Great questions.</p>
<h2>What is the Part 107 test?</h2>
<p><img class="right" alt="FAA logo" src="/images/faa.png" style="box-shadow:none;border:none;/>Part 107 is not a test itself - it refers to the section of the Federal Aviation Regulations that governs Unmanned Aircraft Systems. Under these rules, there are four requirements that you must meet in order to become a certified for commercial drone piloting. Three of these requirements are relatively straightforward:</p> <ul> <li>You must be at least 16 years of age.</li> <li>You must be a literate English speaker (exceptions are made for medical reasons)</li> <li>You must be physically and mentally fit to safely operate a drone.</li> </ul>
<p>The fourth requirement is the one you’re probably interested in: you must pass the Remote Pilot Knowledge Test at an FAA-approved testing center. There’s a handy tool for finding the test center nearest you at <a href="http://federaldroneregistration.com/part-107-test-centers">federaldroneregistration.com</a>. </p>
<p>Keep in mind that you only need to take this test if you’re planning to operate a UAV in a commercial capacity. Regardless of whether you’re flying for recreation or for business, though, make sure you <a href="https://registermyuas.faa.gov/">register your drone</a> with the FAA.</p>
<h2>What does the Remote Pilot Test cover?</h2>
<p>If you’re new to aviation, you might be a bit surprised at the knowledge you’re required to demonstrate on this exam. You’ll need to learn about airspace classification, airport operations, aeronautics, radio communication procedures, aerodynamics, flight instruments, navigation, weather theory, and a slew of information about UAS operation and maintenance. </p>
<p>The <a href="https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/phak/">pilot’s handbook</a> provided by the FAA is incredibly detailed. If you’re serious about a career in piloting, make a point of reading this manual. However, it covers so much information that isn’t specific to UAS operation that you’re not likely to find it a helpful preparation guide for the Remote Pilot Knowledge Test. The <a href="https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/media/remote_pilot_study_guide.pdf">study guide for remote pilots</a> is a much better starting place, but be warned - pilots report that they test may cover topics not adequately addressed by this guide.</p>
<h2>How hard is the test, and how can I prepare?</h2>
<p><img class="left" alt="UAV certification exam" src="/images/exam.jpg"/>You may be wondering whether you should invest in a test prep course. A number of piloting schools offer online or in-person training and preparation specific to the Part 107 exam. Some of these prep courses even offer example tests and money-back guarantees if you don’t pass. The value of this investment, of course, depends on your circumstances.</p>
<p>Many first-time pilots find the exam to be more difficult than they expected. UAS pilot regulations are treated with the same rigor as traditional aircraft pilot rules, and in general the same technical jargon, acronyms, and procedures apply. If you have experience as a pilot in another capacity, the FAA’s study guide is likely sufficient. Or, if you’re flexible and are comfortable taking the exam multiple times, then a prep course may still not be necessary. </p>
<p>If, however, you’re new to aviation and need a commercial license for business reasons, the cost of a prep course is probably less than the cost of the time it would take to study on your own and potentially have to retake the exam. Most prep courses are under $200 and can be completed in a few days or less. If you’re becoming certified for an employer, they should be happy to reimburse the course fee. </p>`;
